spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-atguigu-dev
myinfo: 777
---

spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test
